# Generated by Django 4.2.26 on 2025-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('streams', models.BigIntegerField()),
                ('track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('artist_genres', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('explicit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'date', 'position'],
                'indexes': [models.Index(fields=['country'], name='charts_char_country_853d0d_idx'), models.Index(fields=['track_name'], name='charts_char_track_n_727ddd_idx'), models.Index(fields=['artist'], name='charts_char_artist_59a34b_idx'), models.Index(fields=['date'], name='charts_char_date_f27a65_idx')],
            },
        ),
    ]
