# Generated by Django 4.2.26 on 2025-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartentry',
            name='artist',
            field=models.CharField(help_text='Primary artist name for this track.', max_length=255),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='artist_genres',
            field=models.TextField(blank=True, help_text='Optional: genres for the artist, often comma-separated or raw text.'),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='country',
            field=models.CharField(help_text="Country code or name from the original dataset (for example: 'us', 'global').", max_length=100),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in milliseconds.', null=True),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='explicit',
            field=models.BooleanField(default=False, help_text='Whether the track is marked as explicit in the dataset.'),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='position',
            field=models.IntegerField(help_text='Chart position of the track on that date (1 = top position).'),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='streams',
            field=models.BigIntegerField(help_text='Number of streams for this track on that date.'),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='track_id',
            field=models.CharField(help_text='Spotify track identifier from the CSV file.', max_length=100),
        ),
        migrations.AlterField(
            model_name='chartentry',
            name='track_name',
            field=models.CharField(help_text='Human-readable track name.', max_length=255),
        ),
    ]
