# Generated by Django 4.2.26 on 2025-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_chartentry_artist_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chartentry',
            constraint=models.UniqueConstraint(fields=('date', 'country', 'position'), name='unique_chart_row_per_day_country_position'),
        ),
    ]
